FROM ghcr.io/cirruslabs/flutter:stable AS build
WORKDIR /app

COPY pubspec.yaml pubspec.lock ./
RUN git config --global --add safe.directory /app && flutter pub get

COPY . .
ARG SUPABASE_URL=https://api.qouver.com/skyward
ARG SUPABASE_KEY=REDACTED

RUN printf "SUPABASE_URL=%s\nSUPABASE_KEY=%s\n" "$SUPABASE_URL" "$SUPABASE_KEY" > .env && \
    dart run build_runner build --delete-conflicting-outputs && \
    flutter build web --release

FROM alpine:3.20
COPY --from=build /app/build/web /var/www/html
